import type { NextPage } from "next";
import Head from "next/head";
import { HeroSection, SectionOne, SectionThree, SectionTwo } from "../layouts";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title> Home | Blogr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection />
      <SectionOne />
      <SectionTwo />
      <SectionThree />
    </>
  );
};

export default Home;
